# -*- coding: utf-8 -*-
"""augment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y0CmWvs6zEtVenXS4lQ6XxSwyhUHG3a7
"""


import numpy as np
from scipy import misc, ndimage
import keras
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator

gen=ImageDataGenerator(rotation_range=10, width_shift_range=0.1, height_shift_range=0.1, shear_range=0.15, zoom_range=0.1, channel_shift_range=10, horizontal_flip=True)

image_path='/content/drive/My Drive/apps/Train_data'

#Here 1400 images from a single class is taken. Each image is augmented to produce 5 more images.
#Doing more than this at a time is not possible with the computation power available in Google Colab.
#So augmentation was done seperately for all 3 classes.
aug_iter=gen.flow_from_directory(image_path, target_size=(300,300), classes=['cherry'], save_to_dir='/content/drive/My Drive/apps/Train_data/cherry', batch_size=1400)

aug_images=[next(aug_iter)[0] for i in range(5)]



